[build]
commad = "npm run build"
publish = "dist"

[dev]
commad = "npm run dev"
publish = "dist"

[[edge_functions]]
function = "eleventy-edge"
path = "/housing/affordable-housing/*"

[[edge_functions]]
function = "eleventy-edge"
path = "/data/housing/affordable-housing/*"

[[redirects]]
from = "/contrib/affordable-housing/campaigns/*"
to = "/contrib/affordable-housing/changes"
status = 200
force = true

[[redirects]]
from = "/contrib/affordable-housing/next-property/:campaign/:id"
to = "/.netlify/functions/next-property"
status = 200

[[redirects]]
from = "/contrib/affordable-housing/next-property/:campaign"
to = "/.netlify/functions/next-property"
status = 200

[[redirects]]
from = "/housing"
to = "/housing/affordable-housing"
status = 301

[[redirects]]
from = "/housing/affordable-housing/filter"
to = "/housing/affordable-housing"
status = 200
force = true

[[redirects]]
from = "/data/housing/affordable-housing/filter"
to = "/data/housing/affordable-housing"
status = 200
force = true
