[build]
commad = "npm run build"
publish = "dist"
fucntions = "netlify/functions"

[dev]
commad = "npm run dev"
publish = "dist"
fucntions = "netlify/functions"


[[edge_functions]]
function = "eleventy-edge"
path = "/housing/affordable-housing/*"

[[edge_functions]]
function = "eleventy-edge-test"
path = "/test-edge/*"


