[build]
commad = "npm run build"
publish = "dist"
fucntions = "netlify/functions"

[dev]
commad = "npm run dev"
publish = "dist"
fucntions = "netlify/functions"

[[redirects]]
from = "/housing/affordable-housing/filter"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/housing/affordable-housing/changes/submit"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/housing/affordable-housing/changes-serverless/index.html"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/data/housing/affordable-housing/filter"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/housing/affordable-housing/search"
to = "/.netlify/functions/search-housing"
status = 200

[[redirects]]
from = "/housing/affordable-housing/:id"
to = "/.netlify/functions/units"
status = 200

[[redirects]]
from = "/data/housing/affordable-housing/:id"
to = "/.netlify/functions/units"
status = 200

[[redirects]]
from = "/housing/affordable-housing/rawdata/:id"
to = "/.netlify/functions/rawdata"
status = 200

[[redirects]]
from = "/housing/affordable-housing/next-property/:id"
to = "/.netlify/functions/next-property"
status = 200

[[redirects]]
from = "/housing/affordable-housing/changes/digest"
to = "/.netlify/functions/changes-digest"
status = 200
