[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[build.processing]
  skip_processing = true

[dev]
command = "npm run dev"
publish = "dist"
functions = "netlify/functions"

# Branch specific settings
[context.branch-deploy.processing]
  skip_processing = false
[context.branch-deploy.processing.js]
  minify = true
  bundle = false

[[redirects]]
from = "/housing/affordable-housing/tracker"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/housing/affordable-housing/table"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/housing/affordable-housing/filter"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/data/housing/affordable-housing/filter"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/contrib/affordable-housing/campaigns/*"
to = "/contrib/affordable-housing/changes"
status = 200
force = true

[[redirects]]
from = "/contrib/affordable-housing/next-property/:campaign/:id"
to = "/.netlify/functions/next-property"
status = 200

[[redirects]]
from = "/contrib/affordable-housing/next-property/:campaign"
to = "/.netlify/functions/next-property"
status = 200

[[redirects]]
from = "/housing"
to = "/housing/affordable-housing"
status = 301
